# Build settings
baseurl: 
markdown: kramdown
permalink: pretty
keywords: irukanji, psychedelic, electronic, free, download

port: 2525

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :expanded
