# Build settings
baseurl: 
markdown: kramdown
permalink: pretty
keywords: 'irukanji, psychedelic, electronic'

host: 0.0.0.0
port: 1101

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :compressed

# for open graph
basedomain: http://irukanji-music.com
