# Build settings
baseurl: 
markdown: kramdown
permalink: pretty

host: 0.0.0.0
port: 7005

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :compressed

# custom settings
keywords: 'irukanji, psychedelic, electronic'

# for open graph
basedomain: http://irukanji-music.com

