baseurl: 'irukanji-music-jekyll'
exclude: ['README.md', CNAME]

sass:
  sass_dir: assets/css
  style: :compressed

# custom settings
keywords: 'irukanji, psychedelic, electronic'

# for open graph
basedomain: http://irukanji-music.com

