# Build settings
baseurl: 
markdown: kramdown
permalink: pretty
keywords: psychedelic, irukanji, free music, download

port: 2525

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :expanded
